### PR TITLE
Reformatted, Refactored to Ruby idioms

### PR DESCRIPTION
**Pull request by hosh**
1. Two space soft-tabs
2. Use `Autoload`
3. Name files using community conventions
4. Refactored all the code so they are easier to read

There can be still much improvements. For example, the current code does not use `RestClient` params builder, and instead tries to roll it's own. There are a lot of things that could just be streamlined better.

This code is not tested. I'll be doing that when I use this fork's code in my own Rails app. The code should have it's own unit tests though.

### CODE REVIEW

**Comment by javierjulio** [comment]
This looks great @hosh thanks! @synapsepay Bryan had asked for my input on the Ruby lib. It wasn't very Ruby-ish but this is a great first step by Hosh that will help greatly. I would second Hosh's remarks on the HttpClient initializer too. Maybe we can update those comments with TODO's or FIXME's for others to find them easier and help improve the code.

**Comment by hosh** [comment]
@javierjulio sure. I'm going to be working on this more heavily this week so I'll likely open up other PRs as I fix bugs and whatever is needed.

**Comment by milesmatthias** [comment]
Hi @hosh. The folks at @synapsepay asked me for my input as well. I wrote the first ruby client for synapse before they published their own ([synapse_client](https://github.com/milesmatthias/synapse_client)). I haven't upgrade to v3 of the API yet, but I did have a couple of questions for you:

1. Why use `autoload`? I know most ruby versions claim to be thread safe with it now, but it still seems up for debate as to its future use, so that's why most people I've seen stick to using `require`. Practically speaking I've never seen any major speedup from lazy loading the constants, although it sounds good in theory. I get the proposed benefits, I'm just saying are those benefits really worth it when it may get removed still?

2. This client needs to be used by people using ruby 1.9 still, so why the required parameter syntax from Ruby 2.1? (ex: https://github.com/synapsepay/SynapsePayRest-Ruby/pull/2/files#diff-6c3157ec2c00e9d5920e85aad83055c8R26)

**Comment by javierjulio** [comment]
@milesmatthias regarding num 2: those required parameter changes were in the original. Support for Ruby 1.9.3 has long been over. As this is a new lib for a new API version I say keep this current with Ruby 2.x+. It seems like it was created by the @synapsepay team for Ruby 2.x anyway.

**Comment by milesmatthias** [comment]
@javierjulio the required params are only for 2.1 though right? Not even 2.0?

**Comment by javierjulio** [comment]
@milesmatthias that's a good question, I'm not actually sure. I just remembered after reading your comments that I was positive that those code changes were in the original repo code (pre-PR).

**Comment by synapsepay** [comment]
It looks like I forgot to specify a minimum ruby version but I was aiming for 2.0 since they introduced keyword arguments then.

**Comment by javierjulio** [comment]
@synapsepay what's the hold up here? Can we get some feedback so this can be merged in? Happy to help with changes if necessary.

**Comment by hosh** [comment]
@javierjulio @milesmatthias I'm pretty agnostic to whether to use keyword parameterization, though I will say this:

(1) Ruby 2.2 has some great garbage collection, better than 2.1 or 2.0. I'm fortunate that I won't have to support something below that. If I submit patches here in the future, I'll avoid keyword parameterization.
(2) 1.9 is getting deprecated.

About autoload: it's not really about a speed-up. The issue with autoload being non-thread-safe is a kind of an urban myth: Rails autoload is not thread-safe, Ruby autoload depends.

I've written Ruby gems using `require` without autoload. Maintaining them is a pain. However, I'm agnostic to this as well. I use autoload in the work I use, I go with what the gem maintainer will want unless it is obviously outside the community norms.

I think there are bigger, more important questions to ask about this. For example, the call interface for the Ruby library could be improved a lot.

**Comment by javierjulio** [comment]
I'm with @hosh on this but honestly I would push for Ruby 2.1+ as required keyword arguments are very useful. I'm not familiar with using `require` over `autoload` so I will defer to you all. Agreed, the library interface could be improved a good deal. The changes here are a good start. Also needs to have error handling which I started on in #3. I'd love to do more to get this to move forward.

**Pull request merged**
